//! Schema template generation for decision-log artifacts
//!
//! This module provides the SchemaTemplate trait for YAML template generation.
//! In Phase 2, template implementations are auto-generated by the SchemaTemplate
//! derive macro (#[derive(SchemaTemplate)]) from struct definitions.
//!
//! The macro generates exactly the same templates that were manually written in Phase 1,
//! ensuring no divergence between code and generated templates.

/// Trait for exporting schema templates
///
/// Types implementing this trait can generate human-readable YAML templates
/// that show the expected structure and field types for serialization.
///
/// Implementations are auto-generated by the #[derive(SchemaTemplate)] macro
/// in diffviz-schema-macro crate. The macro inspects struct definitions and
/// generates templates matching the struct's field structure and types.
pub trait SchemaTemplate {
    /// Generate a YAML template showing the schema structure with placeholders
    fn yaml_template() -> String;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entities::decision::DecisionLog;
    use serde_yaml::Value;

    #[test]
    fn template_parses_as_valid_yaml() {
        let template = DecisionLog::yaml_template();
        let result: Result<Value, _> = serde_yaml::from_str(&template);
        assert!(
            result.is_ok(),
            "Template should parse as valid YAML, but got: {:?}",
            result.err()
        );
    }

    #[test]
    fn template_contains_required_fields() {
        let template = DecisionLog::yaml_template();
        assert!(
            template.contains("commit:"),
            "Template should contain 'commit' field"
        );
        assert!(
            template.contains("decisions:"),
            "Template should contain 'decisions' field"
        );
        assert!(
            template.contains("number:"),
            "Template should contain 'number' field in decision"
        );
        assert!(
            template.contains("title:"),
            "Template should contain 'title' field in decision"
        );
        assert!(
            template.contains("rationale:"),
            "Template should contain 'rationale' field in decision"
        );
        assert!(
            template.contains("code_impacts:"),
            "Template should contain 'code_impacts' field"
        );
        assert!(
            template.contains("file:"),
            "Template should contain 'file' field in code impact"
        );
        assert!(
            template.contains("reasoning:"),
            "Template should contain 'reasoning' field"
        );
        assert!(
            template.contains("line_ranges:"),
            "Template should contain 'line_ranges' field"
        );
        assert!(
            template.contains("start:"),
            "Template should contain 'start' field in line range"
        );
        assert!(
            template.contains("end:"),
            "Template should contain 'end' field in line range"
        );
    }

    #[test]
    fn template_structure_matches_decision_log() {
        let template = DecisionLog::yaml_template();
        // Verify we can parse the template back as a DecisionLog
        // (it has example values so won't fully validate, but should parse structurally)
        let result = serde_yaml::from_str::<serde_yaml::Value>(&template);
        assert!(result.is_ok(), "Template should be parseable as YAML");

        let value = result.unwrap();
        assert!(
            value.get("commit").is_some(),
            "Template should have 'commit' key at root"
        );
        assert!(
            value.get("decisions").is_some(),
            "Template should have 'decisions' key at root"
        );

        let decisions = &value["decisions"];
        assert!(
            decisions.is_sequence(),
            "decisions should be a sequence/array"
        );
    }
}
